### ISSUE TITLE
make a github page to host the game

### ISSUE THREAD

**Issue by sethbattin** [Bridget3/sunbirds-game#5]
We should make this game available by hosting it on a github page.

I will work on this.

**Comment by Bridget3** [comment]
ok

**Comment by Bridget3** [comment]
sounds good

**Comment by Bridget3** [comment]
you do that

**Comment by Bridget3** [comment]
how will you?

**Comment by sethbattin** [comment]
It's done.  i put it on the readme, too.

https://bridget3.github.io/sunbirds-game/sunbirds.html
